config/routes.rb
Rails.application.routes.draw do
  root 'pairs#index'
  get '/', to: 'pairs#index', as: 'pairs'
  get 'image_form', to: 'pairs#image_form', as: 'image_form'
  post 'upload', to: 'pairs#upload', as: 'upload_pairs'

  get 'telephones', to: 'telephones#index', as: 'telephones'
  post 'call', to: 'telephones#call', as: 'call'
  post 'record', to: 'telephones#record', as: 'record'
end

app/models/recording.rb
class Recording < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  def index
  end

  def image_form
  end

  def upload
    return redirect_to pair_path, alert: "入力項目が空ですよ!" if params[:text].blank? || params[:image].blank?

    text_data = base64_text
    image_data = params[:image]
    sound_url = params[:sound]

    result = upload_data(text_data, sound_url, image_data)

    if result["flag"] == 'success'
      redirect_to pair_path, notice: "秘密のメッセージ「#{text_data}」と画像が送られました☆"
    else
      redirect_to pair_path, alert: "#{result["txt"]} #{result["image"]}"
    end
  end

  private
    def pair_params
      params.require(:pair).permit(:text, :image)
    end

    def base64_text
      Base64.encode64(params[:text])
    end

    def upload_data(text, sound, image)
      path = resize_image(image)
      connection = Faraday::Connection.new(url: 'http://pair.malkdesign.com/' ) do |conn|
        conn.request :multipart
        conn.adapter :net_http
      end

      params = {
        text: text,
        sound: sound, 
        picture: Faraday::UploadIO.new(path, 'image/jpg') 
      }
      res = connection.post '/check.php', params
      return JSON.parse(res.body)
    end

    def resize_image(image)
      img = Magick::Image.from_blob(image.tempfile.read).shift
      img = img.resize_to_fit(1000, 420)
      f = Tempfile.new('tmp')
      img.write(f.path)
      f.path
    end

end

app/controllers/telephones_controller.rb
class TelephonesController < ApplicationController
  protect_from_forgery except: :record
  
  def index
    #データベースから保存した音声データを取得してViewに渡してください！
  end

  def call
    account_sid = 'ご自身のアカウント！'
    auth_token = 'アカウントのトークン！'
    
    tel = params[:tel]
    tel.gsub!(/^0/, '+81')

    client = Twilio::REST::Client.new account_sid, auth_token
    client.calls.create(
      from: '+815031597307',
      to: tel,
      url: record_url
    ) 
    redirect_to telephones_path
    
  end

  def record
    response = ""
    if params['RecordingUrl'].present?
      response = Twilio::TwiML::Response.new do |r|
        Recording.create!(url: params['RecordingUrl'])
        r.Say 'メッセージを再生して保存します', voice: 'alice', language: 'ja-jp'
        r.Play params['RecordingUrl']
      end
    else
      response = Twilio::TwiML::Response.new do |r|
        r.Say '録音を開始します。終わりましたらシャープを押してください', voice: 'alice', language: 'ja-jp'
        r.Record maxLength: '30', action: record_url, method: 'post', finishOnKey: '#'
      end
    end
    render text: response.text
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/telephones_helper.rb
module TelephonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pair Demo - Top Page -</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pairs/image_form.html.erb
<aside class="callout">
  <div class="text-vertical-center">
    <h1>Upload your Images</h1>
  </div>
</aside>

<div class="form" style="margin: 100px 100px 0;">
<% if flash[:notice].present? %>
  <h4 class="text-primary" style="margin-bottom: 50px"><%= flash[:notice] %></h4>
<% end %>
<% if flash[:alert].present? %>
  <h4 class="text-danger" style="margin-bottom: 50px"><%= flash[:alert] %></h4>
<% end %>
<%= bootstrap_form_tag url: upload_pairs_path do |f| %>
  <%# ここに二人の名前を入れる用のinput boxを作ってください %>
  <%#= f.collection_select :sound, @ここにデータベースからレコードデータを全て取得してください@, :url, :created_at %>
  <%# ここに二人の写真を入れる用のフィールドを作ってください %>
  <%= f.submit 'Upload' %>
<% end %>
</div>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1 text-center">
        <br>
        <hr class="small">
        <p class="text-muted">Copyright &copy; Your Website 2015</p>
      </div>
    </div>
  </div>
</footer>

app/views/pairs/index.html.erb
<header id="top" class="header">
  <div class="text-vertical-center">
    <h1>Enjoy Programing</h1>
    <h3>This is your first experience of pair programming.</h3>
    <%# /telephones がリンク先URL。Railsのmethod使ってくださいね %>
    <a href="" class="btn btn-dark btn-lg">Step Rec</a>
    <br><br>
    <%# /image_form がリンク先URL。Railsのmethod使ってくださいね %>
    <a href="" class="btn btn-dark btn-lg">Step Post</a>
  </div>
</header>

<section id="about" class="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>This event gives us the wonderful experience!</h2>
        <p class="lead">
        Pair programming (sometimes referred to as peer programming) is an agile software development technique 
        in which two programmers work as a pair together on one workstation. 
         <%= link_to 'See more', 'https://en.wikipedia.org/wiki/Pair_programming' ,target: "_blank" %></p>
      </div>
    </div>
  </div>
</section>

<aside class="call-to-action bg-primary">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h3>The button below is just example.</h3>
        <a href="#" class="btn btn-lg btn-light">Click Me!</a>
      </div>
    </div>
  </div>
</aside>

<section id="contact" class="map" style="margin:50px;">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.6188387443435!2d139.70040129999998!3d35.68638625!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188ccfeec9a793%3A0x65aaa649827e761e!2z44CSMTUxLTAwNTMg5p2x5Lqs6YO95riL6LC35Yy65Luj44CF5pyo77yS5LiB55uu77yS4oiS77yRIOWwj-eUsOaApeOCteOCtuODs-OCv-ODr-ODvA!5e0!3m2!1sja!2sjp!4v1442024709504"  width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
  <br />
  <small>
    <a href="https://www.google.co.jp/maps/place/%E3%80%92151-0053+%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B8%8B%E8%B0%B7%E5%8C%BA%E4%BB%A3%E3%80%85%E6%9C%A8%EF%BC%92%E4%B8%81%E7%9B%AE%EF%BC%92%E2%88%92%EF%BC%91+%E5%B0%8F%E7%94%B0%E6%80%A5%E3%82%B5%E3%82%B6%E3%83%B3%E3%82%BF%E3%83%AF%E3%83%BC/@35.6863862,139.7004013,16z/data=!4m2!3m1!1s0x60188ccfeec9a793:0x65aaa649827e761e"</a>
  </small>
  </iframe>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1 text-center">
        <a href="#" class="btn btn-lg btn-dark">Go to Top</a>
        <ul class="list-unstyled">
        </ul>
        <br>
        <hr class="small">
        <p class="text-muted">Copyright &copy; Your Website 2015</p>
      </div>
    </div>
  </div>
</footer>

app/views/telephones/index.html.erb
<aside class="callout">
  <div class="text-vertical-center">
    <h1>Call your phone</h1>
  </div>
</aside>

<div class="form" style="margin: 100px 100px 0;">
<% if flash[:notice].present? %>
  <h4 class="text-primary" style="margin-bottom: 50px"><%= flash[:notice] %></h4>
<% end %>
<% if flash[:alert].present? %>
  <h4 class="text-danger" style="margin-bottom: 50px"><%= flash[:alert] %></h4>
<% end %>
<%# URLのパスを適切なものに変更してください! %>
<%# テキストフィールド追加して電話番号を入力できるように  %>
<%= bootstrap_form_tag url: '/' do |f| %>
  <%= f.submit 'Call' %>
<% end %>
</div>

<div style="margin:50px 100px 100px;">
  <table class="table table-striped">
    <tr>
      <th>作成日時</th>
      <th>音声</th>
    </tr>
<%# テストで作成した音声の作成日とURLをテーブルに複数出力してください  %>
  </table>
<div>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1 text-center">
        <br>
        <hr class="small">
        <p class="text-muted">Copyright &copy; Your Website 2015</p>
      </div>
    </div>
  </div>
</footer>